version: '3'
services:
  wizzer-db:
    container_name: wizzer
    image: postgres:15.3
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
