version: '3'
services:
  wizzer-db:
    container_name: wizzer
    image: postgres:15.3
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5460:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=wizzer-db
